version: '2'

services:
    jenkins:
      build: ./jenkins/
      restart: unless-stopped
      expose:
        - "8080"
        - "50000"
      environment:
        - JENKINS_OPTS=--prefix=/jenkins
